### PR TITLE
## 2018-03-24 Fix Issue #29

### PR DESCRIPTION
**Pull request by Smurf-IV**
## 2018-03-24 Fix Issue #29
* MessageBox taking a Null window owner (via default API's / null start / No KryptonManager loaded)
* Sort out the Toolkit examples to use the new dll locations
* Remove `BootstrapperPackage` .Net 3.5 nonsense from projects
* Remove hard coded build `Output Paths`

### CODE REVIEW

**Comment by Smurf-IV** [comment]
Is there a way, I can work on the this code directly,
Because it seems that "My fork" has got so confused, when merging to it, that when I merge changes back, it includes the original merge again.

Git is confusing sometimes.. I'm used to RTC and TFS ! and I don't remember SVN being like this (But then that was along time ago!)

**Comment by Wagnerp** [comment]
I've noticed the same. Would you like me to create a different branch, so you can merge the changes there instead of `master`?

**Comment by Smurf-IV** [comment]
Ok.
I suppose the other way is to scrap my branch and re-fork,
Might be worth a try.

**Comment by Wagnerp** [comment]
I have made a copy of your fork, so I can merge changes in the meantime.

**Comment by Smurf-IV** [comment]
Ok, I have dropped and recreated my fork, as the Re-mastering steps outlined by others did not seem to cope.
I think it might have been when i re-focused my branch to pull in the others fixes from the Krypton ComponentSource a while ago.
This item can now be closed. And I'm back to the Help Trawl Through!

**Comment by Wagnerp** [comment]
I'll be focusing more on the `Extended Toolkit` got quite an annoying bug with it at the moment.

**Pull request merged**
